In [2]:
import numpy as np

In [18]:
n_x = 3
n_parents = 4
parents = np.arange(12).reshape(4,3)
parents

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## Single Child

In [19]:
single_child_select = np.random.choice(n_parents, replace=True, size=n_x)
single_child_select

array([0, 0, 1])

In [20]:
parents[single_child_select, np.arange(n_x)]

array([0, 1, 5])

## Many Children

In [21]:
n_kids = 10
child_select = np.random.choice(n_parents, replace=True, size=(n_kids, n_x))
child_select

array([[3, 3, 2],
       [2, 3, 1],
       [2, 0, 2],
       [2, 2, 3],
       [1, 3, 2],
       [3, 1, 2],
       [0, 0, 2],
       [0, 3, 0],
       [3, 1, 0],
       [3, 1, 0]])

In [22]:
parents[child_select, np.arange(n_x)]

array([[ 9, 10,  8],
       [ 6, 10,  5],
       [ 6,  1,  8],
       [ 6,  7, 11],
       [ 3, 10,  8],
       [ 9,  4,  8],
       [ 0,  1,  8],
       [ 0, 10,  2],
       [ 9,  4,  2],
       [ 9,  4,  2]])